CREATE TABLE IF NOT EXISTS emails (
  id SERIAL PRIMARY KEY,
  subject VARCHAR(255),
  recipient VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS events (
  id SERIAL PRIMARY KEY,
  email_id INTEGER REFERENCES emails(id),
  type VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
